sudo: required

services:
  - docker

script:
- && docker build . -t xushenglee/solo:original

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push xushenglee/solo
