language: bash

sudo: required

services:
  - docker

script:
  - docker build -t xushenglee/solo:original .

after_script:
  - docker login --username="$DOCKER_PASSWORD" -p="$DOCKER_USERNAME" dockerhub
  - docker push xushenglee/solo:original

