language: bash

sudo: required

services:
  - docker

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

script:
  - docker build -t xushenglee/solo:original .

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xushenglee/solo:original

